# Generated by Django 2.2.10 on 2020-02-13 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_approved_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='approved_comment',
        ),
    ]
